version: '3'
services:
  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      - CONFIG_SERVER_REPOSITORY=https://github.com/ranjan-projects/nutritionix-configuration
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - my-network

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  user-services:
    image: user-services
    container_name: user-services
    build:
      context: ./user-services
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
      - CONFIG_SERVER_HOST=http://config-server:8888
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - config-server
      - eureka-server
      - mysql-db
    networks:
      - my-network

  wishlist-services:
    image: wishlist-services
    container_name: wishlist-services
    build:
      context: ./wishlist-services
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
      - CONFIG_SERVER_HOST=http://config-server:8888
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - my-network

  auth-services:
    image: auth-services
    container_name: auth-services
    build:
      context: ./auth-services
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
      - CONFIG_SERVER_HOST=http://config-server:8888
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - my-network

  nutrition-services:
    image: nutrition-services
    container_name: nutrition-services
    build:
      context: ./nutrition-services
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
      - CONFIG_SERVER_HOST=http://config-server:8888
    ports:
      - "8084:8084"
    restart: on-failure
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - my-network

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - AUTH_SERVICE_URL=http://auth-services:8083
      - CONFIG_SERVER_HOST=http://config-server:8888
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - eureka-server
      - user-services
      - wishlist-services
      - auth-services
      - nutrition-services
      - config-server
    networks:
      - my-network

  react-app:
    image: react-nutritionix-app
    container_name: react-nutritionix-app
    build:
      context: ./react-nutritionix-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - api-gateway

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
